### ISSUE TITLE
"Search" in toolbar is not working

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/Evergreen#99] opened 2017-11-02 07:01 UTC
Git @ 911e6b0

Steps:
1. Click on "Search" input field in toolbar.
2. Type something.

What happened:
Nothing.

Expected result:
Search results are shown.

**Comment by brentsimmons** [comment] 2017-11-04 22:47
Good find! Duplicate of #21.

**Closed by brentsimmons** 2017-11-04 22:47 UTC
