### ISSUE TITLE
can't drag feed into folder

### ISSUE THREAD

**Issue by mf3k** [brentsimmons/Evergreen#345] opened 2018-02-14 13:29 UTC
Can create and place feed into a folder, but cannot drag existing feed to a folder.

High Sierra 10.13.3 (17D47).

**Comment by brentsimmons** [comment] 2018-02-14 20:56
Good catch! This will definitely get fixed for 1.0 alpha.

Duplicate of #13.

**Closed by brentsimmons** 2018-02-14 20:56 UTC
